rotation_rectifiers:
  ACCAD:
    - [-1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0]
    - [0.0, 1.0, 0.0]
  
  BEAT2:
    - [1.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0]
    - [0.0, 0.0, 1.0]
  
  BMLmovi:
    - [0.0, 0.0, 1.0]
    - [1.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0]
  
  BMLrub:
    - [0.0, 0.0, 1.0]
    - [1.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0]
  
  CMU:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  CNRS:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  DFaust:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  EKUT:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  EyesJapanDataset:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  Eyes_Japan_Dataset:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  GRAB:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  HumanEva:
    - [0.0, 0.0, 1.0]
    - [1.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0]
  
  KIT:
    - [0.0, 0.0, -1.0]
    - [-1.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0]
  
  HDM05:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  MOYO:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  MPI_HDM05:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  MPI_Limits:
    - [0.0, 0.0, -1.0]
    - [-1.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0]
  
  PosePrior:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  MoSh:
    - [-1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0]
    - [0.0, 1.0, 0.0]
  
  MPI_mosh:
    - [-1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0]
    - [0.0, 1.0, 0.0]
  
  SAMP:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  SFU:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  SOMA:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  SSM:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  TCD_handMocap:
    - [0.0, 0.0, 1.0]
    - [1.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0]
  
  TCDHands:
    - [0.0, 0.0, 1.0]
    - [1.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0]
  
  TotalCapture:
    - [0.0, 0.0, 1.0]
    - [1.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0]
  
  Transitions:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]
  
  WEIZMANN:
    - [1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 1.0, 0.0]